name: CI Medical Stock Monitor

on:
  schedule:
    # 毎日午前9時と午後5時に実行 (UTC)
    # 日本時間では毎日午後6時と午前2時
    - cron:  '0 0,8 * * *'
  workflow_dispatch:

jobs:
  monitor_stock:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 selenium

    - name: Run stock monitor script
      id: run_script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        CI_MEDICAL_USERNAME: ${{ secrets.CI_MEDICAL_USERNAME }}
        CI_MEDICAL_PASSWORD: ${{ secrets.CI_MEDICAL_PASSWORD }}
        PRODUCT_URL: https://www.ci-medical.com/dental/catalog_item/801Y697
        LOGIN_URL: https://www.ci-medical.com/login
      id: run_script
      run: |
        python stock_monitor.py
        echo "status=$(cat last_stock_status.txt)" >> $GITHUB_OUTPUT

    - name: Create Issue on Stock Available
      if: success() && steps.run_script.outputs.status == '在庫あり'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'CI Medical 在庫通知: 在庫あり',
            body: 'CI Medicalの製品ページ (${{ env.PRODUCT_URL }}) の在庫状況が「在庫あり」に変化しました。\n確認してください。'
          })



