
name: CI Medical Stock Monitor

on:
  schedule:
    # 毎日午前9時と午後5時に実行 (UTC)
    # 日本時間では毎日午後6時と午前2時
    - cron:  '0 0,8 * * *'
  workflow_dispatch:

jobs:
  monitor_stock:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 selenium PyGithub

    - name: Run stock monitor script
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        CI_MEDICAL_USERNAME: ${{ secrets.CI_MEDICAL_USERNAME }}
        CI_MEDICAL_PASSWORD: ${{ secrets.CI_MEDICAL_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python stock_monitor.py


